apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress-nginx-components.yaml
- sync.yaml
patches:
  - path: ingress-nginx-cm-patch.yaml 
    target:
      kind: ConfigMap
  - path: ingress-nginx-svc-patch.yaml 
    target:
      kind: Service